### ISSUE TITLE
Error:Project :samremotecommon declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :nodestyle.

### ISSUE THREAD

**Issue by fernandodeveloper** [mkg20001/SamRemote#1]
Error:Project :samremotecommon declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :nodestyle.

**Comment by mkg20001** [comment]
You need to run those commands in the app folder or re-clone the repo recursive:
```
git submodule init
git submodule update
```
Then that error should go away
